### ISSUE TITLE
Tabs 컴포넌트

### ISSUE THREAD

**Issue by hckang80** [uprise-fin/dndn-svelte-ui#1]
## 디자인
https://www.figma.com/file/H2uP5oFWb1lXIapvdZvWV3/DDS-2.0?type=design&node-id=514-19225&mode=design&t=fkcYyzys3TIBlq3I-0

## 작업사항
Button 처럼 Tabs 디렉터리를 생성해서 진행하면 되겠습니다.

## 기타
완성보다는 경험을 쌓는다는 의미로 진행하면 되겠습니다.
(물론, 완성도 해주면 더 좋습니다. ^^)

**Comment by ellen-uprise** [comment]
@jaden-uprise 이 이슈는 종료된 이슈인가요?
